settings:
  title: 'Status Page'
  url: 'https://status.jing.rocks' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: jing-rocks # unique identifier
    name: jing.rocks
    description: "Jing's personal website" # default=empty
    url: 'https://jing.rocks/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: repo-jing-rocks-80
    name: http://repo.jing.rocks
    description: 'Mirrors for various GNU/Linux and GNU/Linux-libre distributions'
    url: 'http://repo.jing.rocks/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: repo-jing-rocks-443
    name: https://repo.jing.rocks
    description: 'Mirrors for various GNU/Linux and GNU/Linux-libre distributions'
    url: 'https://repo.jing.rocks/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: jitsi-jing-rocks
    name: https://jitsi.jing.rocks
    description: 'My jitsi-meet server instance'
    url: 'https://jitsi.jing.rocks/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: jellyfin-jing-rocks
    name: https://jellyfin.jing.rocks
    description: 'My jellyfin media server instance'
    url: 'https://jellyfin.jing.rocks/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false

  - id: nextcloud1-jing-rocks
    name: https://nextcloud1.jing.rocks
    description: 'My nextcloud server instance'
    url: 'https://nextcloud1.jing.rocks/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: lists-jing-rocks
    name: https://lists.jing.rocks/
    description: 'My mail server'
    url: 'https://lists.jing.rocks/mailman3/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false
